#define FACTION_LONERS "Loners"
#define FACTION_BANDITS "Bandits"
#define FACTION_DUTY "Duty"
#define FACTION_FREEDOM "Freedom"
#define FACTION_MERC "Mercenaries"
#define FACTION_MONOLITH "Monolith"
#define FACTION_CLEARSKY "Clear Sky"
#define FACTION_ECOLOGIST "Ecologist"
#define FACTION_RENEGATE "Renegades"
#define FACTION_MILITARY "Security Service of Ukraine"
